name: dox
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-76.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  implicitly_animated_reorderable_list: ^0.4.2
  material_design_icons_flutter: ^5.0.6595
  material_floating_search_bar: ^0.3.6
  provider: ^6.0.2
  cupertino_icons: ^1.0.4
  photo_view: ^0.12.0
  flutter_dotenv: ^5.0.2
  document_scanner_flutter: ^0.2.7
  simple_speed_dial: ^0.1.3
  file_picker: ^4.4.0
  motion_toast: ^2.1.1
  lottie: ^1.2.2
  quiver: ^3.0.1+1
  syncfusion_flutter_pdfviewer: ^19.4.54-beta
  cached_network_image: ^3.2.0
  web_socket_channel: ^2.1.0
  get_it: ^7.2.0
  logging: ^1.0.2
  google_sign_in: ^5.4.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  test: ^1.20.1
  mock_web_server: ^5.0.0-nullsafety.1
  stream_channel: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - '.simulator.env'
    - '.realdevice.env'
    - './assets/app-bar.webp'
    - './assets/splash-screen.json'
    - './assets/incorrect-file.json'
