name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_core:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: ./core

    - name: Run cargo-make
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - name: Run tests
      working-directory: ./core
      run: cargo make --profile ci all
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build_client:
    defaults:
      run:
        working-directory: ./client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format . --set-exit-if-changed
      - run: flutter test
