name: client-ci

on:
  push:
    branches: [ master ]
    paths:
      - "client/**"
      - ".github/workflows/client-ci.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "client/**"
      - ".github/workflows/client-ci.yml"

env:
  ENV: realdevice

jobs:
  build_client:
    defaults:
      run:
        working-directory: ./client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: |
          # setup env files
          # TODO: fix <ip-addr>
          touch .simulator.env
          echo "BASE_URL=http://<ip-addr>:8000" >> .realdevice.env
          echo "WEBSOCKET_URL=ws://<ip-addr>:8001" >> .realdevice.env
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter format . --set-exit-if-changed
      - run: flutter test
