name: core-ci

on:
  push:
    branches: [ master ]
    paths:
      - "core/**"
      - ".github/workflows/core-ci.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "core/**"
      - ".github/workflows/core-ci.yml"

env:
  ENV: realdevice

jobs:
  build_core:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install libpoppler-glib-dev
    - run: sudo apt install libleptonica-dev libtesseract-dev clang
    - run: sudo apt install tesseract-ocr-pol
    - run: wget https://github.com/rui314/mold/releases/download/v1.4.2/mold-1.4.2-x86_64-linux.tar.gz && sudo tar -xf ./mold-1.4.2-x86_64-linux.tar.gz -C /usr/bin && sudo mv /usr/bin/mold-1.4.2-x86_64-linux /usr/bin/mold
    - run: which ls
    - run: mold --version
    - name: Checkout Repo
      uses: actions/checkout@v2

    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: ./core

    - name: Run cargo-make
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - name: Run tests
      working-directory: ./core
      run: cargo make --profile ci all
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        DOX_CLIENT_ID: ${{ secrets.DOX_CLIENT_ID }}
        DOX_CLIENT_SECRET: ${{ secrets.DOX_CLIENT_SECRET }}
        DOX_REFRESH_TOKEN: ${{ secrets.DOX_REFRESH_TOKEN }}
        RUST_LOG: debug
